// This class was auto generated by easy-resources-maven-plugin.
// December 17, 2023 at 6:10:00 PM EST
package com.jgazula.test;

import java.lang.String;
import java.math.BigDecimal;
import java.util.ResourceBundle;

public class TestClass {
    private final String firstPrivateVar;

    private final ResourceBundle secondPrivateVar;

    private final BigDecimal thirdPrivateVar;

    private final String fourthPrivateVar;

    public TestClass(String firstPrivateVar, ResourceBundle secondPrivateVar,
            BigDecimal thirdPrivateVar, String fourthPrivateVar) {
        this.firstPrivateVar = firstPrivateVar;
        this.secondPrivateVar = secondPrivateVar;
        this.thirdPrivateVar = thirdPrivateVar;
        this.fourthPrivateVar = fourthPrivateVar;
    }
}