// This class was auto generated by easy-resources-maven-plugin.
// December 17, 2023 at 4:58:00 PM EST
package com.jgazula.test;

import java.lang.String;

public class TestClass {
    public static final String FIRST_STRING_CONSTANT_KEY = "firstStringConstantValue";

    public static final String SECOND_STRING_CONSTANT_KEY = "secondStringConstantValue";

    public static final String THIRD_STRING_CONSTANT_KEY = "thirdStringConstantValue";
}