// This class was auto generated by easy-resources-maven-plugin.
// December 18, 2023 at 3:00:00 AM EST
package com.jgazula.test;

import java.lang.Object;
import java.lang.String;
import java.math.BigDecimal;
import java.text.MessageFormat;
import java.util.Date;
import java.util.ResourceBundle;

public class TestClass {
    private final ResourceBundle resourceBundle;

    public TestClass(ResourceBundle resourceBundle) {
        this.resourceBundle = resourceBundle;
    }

    public String myTestKey(BigDecimal arg0, Date arg1, String arg2, int arg3) {
        String message = this.resourceBundle.getString("my.test.key");
        Object[] messageArguments = {arg0, arg1, arg2, arg3};
        return new MessageFormat(message, this.resourceBundle.getLocale()).format(messageArguments);
    }
}