// This class was auto generated by easy-resources-maven-plugin.
// October 7, 2023 at 3:20:23 PM EST
package com.jgazula.test;

import java.util.ResourceBundle;

public class TestClass {
    private final ResourceBundle resourceBundle;

    public TestClass(ResourceBundle resourceBundle) {
        this.resourceBundle = resourceBundle;
    }
}